name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: rustup install beta-i686-unknown-linux-gnu
      - run: |
          cargo new foo
          cd foo
          echo 'log = "0.4.11"' >> Cargo.toml
          cargo +beta-i686-unknown-linux-gnu fetch
